#! /bin/bash
# $Id$
set -o errexit

CASE=test-exports
AGPROG='Exports ("'$CASE'-i.in")
Read (.)'
# kludge: break up the output into lines
S1='s/\$\[/\
\$\[/g'
S2='s/,\] $/,\
\] /g'

echo "$AGPROG" | ./ag_exports | sed -e 1d >$CASE.ycp.tmp
sed -e "$S1" -e "$S2" $CASE.ycp.tmp > $CASE-i.out.tmp
diff -u $CASE-i.out.tmp $CASE-i.out

echo -n 'Exports ("'$CASE'-o.out.tmp")
Write (.,' `cat $CASE.ycp.tmp` ')' \
    | ./ag_exports >/dev/null
diff -u $CASE-o.out.tmp $CASE-o.out
